/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shopping.cart.graddle.app;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
